name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 900

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          # Debug output
          ls -la ~/.ssh/ec2_key.pem
          echo "SSH key permissions set"

      - name: Deploy to EC2
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
        run: |
          # Debug EC2 instance info
          echo "Getting EC2 information..."
          EC2_PUBLIC_DNS=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --query 'Reservations[*].Instances[*].PublicDnsName' \
            --output text)
          echo "EC2 Public DNS: $EC2_PUBLIC_DNS"

          # Debug known_hosts
          echo "Adding to known_hosts..."
          ssh-keyscan -H $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
          echo "known_hosts content:"
          cat ~/.ssh/known_hosts

          # Test SSH connection with verbose output
          echo "Testing SSH connection..."
          ssh -v -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USERNAME }}@$EC2_PUBLIC_DNS 'echo "SSH connection successful"'
        
          # If SSH test succeeds, run deployment
          echo "Starting deployment..."
          ssh -v -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USERNAME }}@$EC2_PUBLIC_DNS 'bash -s' < scripts/deploy.sh
        
          # Print deploy.sh content for debugging
          echo "Content of deploy.sh:"
          cat scripts/deploy.sh